"""Report envelope v1: an in-toto Statement v1 wrapping one tool result.

The shared format is documented in ``docs/report-envelope.md`` and described
by ``schemas/report-envelope.v1.json``. Reports are written as canonical JSON
(UTF-8, sorted keys, no insignificant whitespace, one trailing newline) so the
file's SHA-256 is stable and the report can be signed with standard tooling.
"""

from __future__ import annotations

import hashlib
import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Literal

from . import __version__

STATEMENT_TYPE = "https://in-toto.io/Statement/v1"
TOOL_NAME = "toolkit-data-contracts"
PREDICATE_TYPE = f"https://github.com/AKIVA-AI/{TOOL_NAME}/report/v1"

Verdict = Literal["pass", "fail", "error"]


def sha256_file(path: Path) -> str:
    """Hex SHA-256 of a file's bytes, read in chunks."""
    h = hashlib.sha256()
    with Path(path).open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def resource_ref(name: str, path: Path) -> dict[str, Any]:
    """An in-toto ResourceDescriptor with a sha256 digest of ``path``."""
    return {"name": str(name), "digest": {"sha256": sha256_file(path)}}


def utc_now_rfc3339() -> str:
    """Current UTC time as RFC 3339 with a ``Z`` suffix and second precision.

    Honors ``SOURCE_DATE_EPOCH`` (reproducible-builds convention) so a report
    can be regenerated byte for byte.
    """
    epoch = os.environ.get("SOURCE_DATE_EPOCH", "").strip()
    if epoch.isdigit():
        moment = datetime.fromtimestamp(int(epoch), tz=timezone.utc)
    else:
        moment = datetime.now(timezone.utc)
    return moment.strftime("%Y-%m-%dT%H:%M:%SZ")


def build_envelope(
    *,
    kind: str,
    subject: list[dict[str, Any]],
    inputs: list[dict[str, Any]],
    verdict: Verdict,
    exit_code: int,
    summary: dict[str, Any],
    details: dict[str, Any],
) -> dict[str, Any]:
    """Build a report envelope. ``verdict`` and ``exit_code`` must agree.

    Raises:
        ValueError: if the verdict and exit code are inconsistent, or there is
            no subject.
    """
    if verdict not in ("pass", "fail", "error"):
        raise ValueError(f"invalid verdict: {verdict!r}")
    if (verdict == "pass") != (exit_code == 0):
        raise ValueError(f"verdict {verdict!r} is inconsistent with exit code {exit_code}")
    if not subject:
        raise ValueError("a report needs at least one subject")
    return {
        "_type": STATEMENT_TYPE,
        "subject": subject,
        "predicateType": PREDICATE_TYPE,
        "predicate": {
            "tool": {"name": TOOL_NAME, "version": __version__},
            "kind": kind,
            "created_at": utc_now_rfc3339(),
            "verdict": verdict,
            "exit_code": int(exit_code),
            "inputs": inputs,
            "summary": summary,
            "details": details,
        },
    }


def canonical_json(obj: Any) -> str:
    """Canonical JSON text: sorted keys, no insignificant whitespace, trailing newline."""
    return (
        json.dumps(obj, sort_keys=True, separators=(",", ":"), ensure_ascii=False, allow_nan=False)
        + "\n"
    )
